use rand::prelude::IndexedRandom;

const FISH_NAMES: &[&str] = &[
    "anchovy",
    "barracuda",
    "bass",
    "blowfish",
    "bluegill",
    "bonefish",
    "bonito",
    "bream",
    "carp",
    "catfish",
    "clownfish",
    "cod",
    "dace",
    "darter",
    "dorado",
    "drum",
    "eel",
    "flounder",
    "gar",
    "goby",
    "grouper",
    "grunt",
    "guppy",
    "haddock",
    "halibut",
    "herring",
    "lamprey",
    "mackerel",
    "mahi",
    "marlin",
    "minnow",
    "mullet",
    "perch",
    "pike",
    "piranha",
    "pollock",
    "puffer",
    "salmon",
    "sardine",
    "sawfish",
    "shad",
    "shark",
    "snapper",
    "sole",
    "sturgeon",
    "sunfish",
    "swordfish",
    "tarpon",
    "tench",
    "trout",
    "tuna",
    "wahoo",
    "walleye",
    "wrasse",
];

pub fn generate() -> String {
    let mut rng = rand::rng();
    FISH_NAMES.choose(&mut rng).unwrap().to_string()
}
